### PR TITLE
Implement client-side opportunity filtering

### PR DESCRIPTION
**Pull request by frank-cywong**
Attempts to address the bug on grade/group being an OR operation not AND.
Debug print statements are left for debugging.

PR-ing to test behavior on production stack

@Jiangsta

### CODE REVIEW

**Comment by frank-cywong** [comment]
That's the wrong david lol @TheEgghead27

**Comment by thunder-red-star** [comment]
Tested this deploy, filtering is MUCH faster.

Small thing, if you unselect every category, the filters just reset to selecting every category. Is this intended?

**Comment by thunder-red-star** [comment]
Filtering tags is completely broken. Only categories works 🙁 

Will get to this soon!

**Comment by frank-cywong** [comment]
> Filtering tags is completely broken. Only categories works 🙁
> 
> Will get to this soon!

Tbh I don't know what the proper logic for eligibilities should be

Right now its like:
If an opportunity has no group eligibilities then it shows up always
Otherwise then it shows up only if there exists a group eligibility that you picked and it has

I guess general RFC to everyone @TheEgghead27 @thunder-red-star @YBenPan @GandyT about how this should be done

Also could you clarify what's breaking rn?

**Comment by TheEgghead27** [comment]
I remember leaving it with the present behavior because having all boxes checked would exclude opportunities with _no_ group eligibilities (because it would strictly want at least one of those), and giving the user empty results might be confusing when another filter (e.g. search query, topic choice) is in place

**Comment by thunder-red-star** [comment]
We could provide a message stating that no opportunities came up with that filter... I was thinking that if a user wanted to clear all the filters except one and then accidentally cleared the last one, they'd have to re-clear everything again.

**Comment by frank-cywong** [comment]
> We could provide a message stating that no opportunities came up with that filter... I was thinking that if a user wanted to clear all the filters except one and then accidentally cleared the last one, they'd have to re-clear everything again.

Yeah that's something that I should do

**Comment by thunder-red-star** [comment]
We should probably merge this ASAP, I have some cosmetic changes coming down the pipe and I want to avoid merge conflicts

**Comment by thunder-red-star** [comment]
When you are done

**Comment by frank-cywong** [comment]
Looks good now, merging based on discussion in #opportunities on Discord

**Pull request merged**
