### PR TITLE
Add Pagination to Catalog page

### PR DESCRIPTION
**Pull request by TheEgghead27**
Automagically loads next opportunities when scrolling to bottom.

### CODE REVIEW

**Comment by TheEgghead27** [comment]
Depends on https://github.com/stuysu/opportunities-api.stuysu.org/pull/52

**Comment by TheEgghead27** [comment]
In addition, refactor search page options to use checkboxes (for clarity and consistency with other search pages on e-commerce sites)

**Review by Rahuldeb75 — APPROVED** [review]

**Comment by TheEgghead27** [comment]
Thanks, Rahul!
@GandyT do you think these changes are ready?

**Comment by GandyT** [comment]
code looks fine!

**Pull request merged**
