### PR TITLE
Cosmetics and lots of other misc stuff

### PR DESCRIPTION
**Pull request by thunder-red-star**
I did not make eslint fixes, please ignore those. I'll do that tmrw

### CODE REVIEW

**Comment by thunder-red-star** [comment]
You will probably see deploy errors

**Comment by williamvongphan** [comment]
Also readme

**Comment by sonofthomp** [comment]
MERGE THIS FRANK

**Review by williamvongphan — APPROVED** [review]
(reviewing my own thing) at least it works with all the other PRs

**Pull request merged**
